include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Stile
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - unnecessary_const
    - unnecessary_new
    
    # Best practices
    - avoid_print
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - use_key_in_widget_constructors
    - prefer_single_quotes
    - always_declare_return_types
    - always_put_required_named_parameters_first

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
